In [33]:
import pandas as pd 
df = pd.read_excel('../Dataset/CSM_dataset.xlsx')

# ! pip install openpyxl

In [34]:
print(df)

                      Movie  Year  Ratings  Genre      Gross       Budget  \
0                   13 Sins  2014      6.3      8       9130    4000000.0
1            22 Jump Street  2014      7.1      1  192000000   50000000.0
2            3 Days to Kill  2014      6.2      1   30700000   28000000.0
3    300: Rise of an Empire  2014      6.3      1  106000000  110000000.0
4         A Haunted House 2  2014      4.7      8   17300000    3500000.0
..                      ...   ...      ...    ...        ...          ...
226                Child 44  2015      6.4      4    1210000   50000000.0
227                   Aloha  2015      5.5     15   21000000   37000000.0
228     Unfinished Business  2015      5.4      8   10200000   35000000.0
229                War Room  2015      5.4      1   12300000    3000000.0
230             The Gallows  2015      4.4     15   22600000     100000.0

     Screens  Sequel  Sentiment    Views  Likes  Dislikes  Comments  \
0       45.0       1          0  3280543   4632       425       636
1     3306.0       2          2   583289   3465        61       186
2     2872.0       1          0   304861    328        34        47
3     3470.0       2          0   452917   2429       132       590
4     2310.0       2          0  3145573  12163       610      1082
..       ...     ...        ...      ...    ...       ...       ...
226     66.0       1          4  3701061   9325       641      1859
227   2815.0       1         13  7119456  18803      1128      2290
228   2777.0       1          7  3450614   6823       325       409
229      NaN       1         10    66872    400        67       201
230   2720.0       1         -5   659772   2841       431       606

     Aggregate Followers
0              1120000.0
1             12350000.0
2               483000.0
3               568000.0
4              1923800.0
..                   ...
226                  NaN
227                  NaN
228                  NaN
229                  NaN
230                  NaN

[231 rows x 14 columns]

In [35]:
from IPython.display import display

print("CSM dataset:")
display(df)

CSM dataset:

,Movie,Year,Ratings,Genre,Gross,Budget,Screens,Sequel,Sentiment,Views,Likes,Dislikes,Comments,Aggregate Followers
0,13 Sins,2014,6.3,8,9130,4000000.0,45.0,1,0,3280543,4632,425,636,1120000.0
1,22 Jump Street,2014,7.1,1,192000000,50000000.0,3306.0,2,2,583289,3465,61,186,12350000.0
2,3 Days to Kill,2014,6.2,1,30700000,28000000.0,2872.0,1,0,304861,328,34,47,483000.0
3,300: Rise of an Empire,2014,6.3,1,106000000,110000000.0,3470.0,2,0,452917,2429,132,590,568000.0
4,A Haunted House 2,2014,4.7,8,17300000,3500000.0,2310.0,2,0,3145573,12163,610,1082,1923800.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,Child 44,2015,6.4,4,1210000,50000000.0,66.0,1,4,3701061,9325,641,1859,NaN
227,Aloha,2015,5.5,15,21000000,37000000.0,2815.0,1,13,7119456,18803,1128,2290,NaN
228,Unfinished Business,2015,5.4,8,10200000,35000000.0,2777.0,1,7,3450614,6823,325,409,NaN
229,War Room,2015,5.4,1,12300000,3000000.0,NaN,1,10,66872,400,67,201,NaN
230,The Gallows,2015,4.4,15,22600000,100000.0,2720.0,1,-5,659772,2841,431,606,NaN

In [36]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(
    df, test_size=0.2, random_state=42
)

In [37]:
train.head()

,Movie,Year,Ratings,Genre,Gross,Budget,Screens,Sequel,Sentiment,Views,Likes,Dislikes,Comments,Aggregate Followers
55,Interstellar,2014,8.7,2,188000000,165000000.0,3561.0,1,2,5421705,16635,751,4316,1865000.0
229,War Room,2015,5.4,1,12300000,3000000.0,NaN,1,10,66872,400,67,201,NaN
69,Lucy,2014,6.4,1,127000000,40000000.0,3173.0,1,1,1142964,2346,167,311,NaN
168,Pitch Perfect 2,2015,6.7,8,183000000,29000000.0,3473.0,2,1,9214467,39824,998,1987,7336000.0
109,The Admiral,2014,7.1,2,2590000,9500000.0,1586.0,1,3,134353,280,43,308,NaN

In [38]:
display(test)

,Movie,Year,Ratings,Genre,Gross,Budget,Screens,Sequel,Sentiment,Views,Likes,Dislikes,Comments,Aggregate Followers
218,Southpaw,2015,7.7,1,49500000,3.000000e+07,2772.0,1,6,11476882,40496,1383,4435,NaN
66,Let's Be Cops,2014,6.5,8,82400000,1.700000e+07,1534.0,1,-5,4450824,7315,546,909,2356000.0
9,About Last Night,2014,6.1,8,48600000,1.250000e+07,2253.0,1,0,5218079,11709,532,770,21697300.0
170,Home,2015,6.7,8,177000000,1.350000e+08,3708.0,1,-2,10341783,24413,1675,3426,5070000.0
15,Barefoot,2014,6.6,8,11800,6.000000e+06,18.0,1,2,3915978,6983,247,460,253000.0
200,Paper Towns,2015,6.9,3,31400000,1.200000e+07,3031.0,1,6,2854910,23254,459,1087,4184000.0
25,Cantinflas,2014,6.7,9,6370000,3.000000e+06,382.0,1,3,2902492,9522,558,2296,NaN
196,Hot Pursuit,2015,5.0,1,34500000,3.500000e+07,3003.0,1,2,6964819,26601,1111,1293,1630000.0
154,When the Game Stands Tall,2014,6.6,3,30100000,1.500000e+07,794.0,1,0,280566,477,56,82,585000.0
126,The Hundred-Foot Journey,2014,7.3,8,54200000,2.200000e+07,2023.0,1,11,24809,277,12,52,20700.0
215,Americons,2015,7.3,3,129000,4.000000e+06,14.0,1,0,63724,115,28,14,129000.0
19,Black or White,2014,6.6,3,21600000,9.000000e+06,1823.0,1,-1,1348142,4404,307,1033,888000.0
96,Sabotage,2014,5.7,1,10500000,3.500000e+07,2486.0,1,17,3466458,6096,411,977,3678000.0
178,Trainwreck,2015,6.7,12,105000000,3.500000e+07,3158.0,1,1,9511288,19903,2581,2955,2014000.0
175,Straight Outta Compton,2015,8.3,9,135000000,2.800000e+07,2757.0,1,5,848970,12607,237,1560,55618.0
137,The November Man,2014,6.3,1,25000000,1.500000e+07,2776.0,1,0,1935432,3089,155,567,148000.0
146,The Water Diviner,2014,7.2,3,4190000,2.250000e+07,320.0,1,7,3281842,4968,445,2099,1899400.0
30,Divergent,2014,6.8,2,151000000,8.500000e+07,3936.0,1,-4,463866,3400,152,987,1030000.0
226,Child 44,2015,6.4,4,1210000,5.000000e+07,66.0,1,4,3701061,9325,641,1859,NaN
185,Magic Mike XXL,2015,6.2,8,65900000,1.480000e+07,3355.0,2,7,5128288,18475,858,1579,8392000.0
108,That Awkward Moment,2014,6.1,8,26000000,8.000000e+06,2809.0,1,0,6132551,14539,653,846,11783000.0
162,Yves Saint Laurent,2014,6.2,9,717000,1.200000e+07,2.0,1,0,550734,894,44,77,168700.0
205,Hitman: Agent 47,2015,5.9,8,16100000,3.500000e+07,3261.0,1,10,13154873,46684,3565,8578,209000.0
181,Terminator Genisys,2015,6.8,1,89400000,1.550000e+08,3758.0,5,1,84870,265,13,63,3877901.0
125,The Homesman,2014,6.6,3,2430000,1.600000e+07,4.0,1,2,26528,58,1,8,25748.0
18,Big Hero 6,2014,7.9,12,222000000,1.650000e+08,3761.0,1,29,4700023,14163,538,1293,199800.0
147,The Woman in Black 2: Angel of Death,2014,4.9,3,26500000,1.000000e+06,2602.0,2,-6,698,16,1,9,3086.0
101,Sin City: A Dame to Kill For,2014,6.6,10,13800000,6.500000e+07,2894.0,2,0,5223362,18770,627,2796,8620000.0
104,St. Vincent,2014,7.3,8,44100000,1.300000e+07,18.0,1,20,4176181,9463,310,885,269849.0
84,Not Cool,2014,5.2,8,35700,6.000000e+05,NaN,1,0,5403836,187162,3145,24919,2720000.0
198,Woman in Gold,2015,7.4,10,33300000,1.100000e+07,258.0,1,19,6495,82,3,7,675000.0
60,Jersey Boys,2014,6.9,9,47000000,4.000000e+07,2905.0,1,10,1438350,4028,133,543,27323.0
118,The Expendables 3,2014,6.1,1,39300000,9.000000e+07,90.0,3,0,14453673,33092,1336,5005,1480000.0
45,Gone Girl,2014,8.2,3,168000000,6.100000e+07,3014.0,1,-11,396010,1390,58,342,20640000.0
16,Better Living Through Chemistry,2014,6.3,8,72300,5.000000e+06,25.0,1,0,1391527,2479,146,182,1658900.0
127,The Hunger Games: Mockingjay - Part 1,2014,6.8,2,337000000,1.250000e+08,4151.0,3,2,3305417,14684,332,1176,31030000.0
159,Winter's Tale,2014,6.2,3,22500,6.000000e+07,2965.0,1,0,719976,1312,76,189,1810000.0
119,The Fault in Our Stars,2014,7.9,3,125000000,1.200000e+07,3173.0,1,7,32626778,370552,4752,38363,4240000.0
82,Noah,2014,5.9,1,101000000,1.250000e+08,3567.0,1,6,13661095,41254,3812,18077,1810000.0
144,The Salvation,2014,6.8,3,5000,1.171231e+07,2.0,1,0,253631,170,11,58,NaN
93,RoboCop,2014,6.2,1,58600000,1.000000e+08,3372.0,1,7,3305047,11733,1077,4319,250000.0
194,The Gift,2015,7.6,1,36100000,5.000000e+06,1648.0,1,11,2513544,6970,270,1105,1655987.0
143,The Rover,2014,6.4,10,1110000,1.225000e+07,5.0,1,0,702,1,0,1,9842.0
73,Moms' Night Out,2014,5.4,8,10400000,5.000000e+06,1044.0,1,0,667852,469,38,44,919000.0
113,The Book of Life,2014,7.3,12,50200000,5.000000e+07,12.0,1,9,5165441,17476,871,3229,10364000.0
112,The Best of Me,2014,6.6,3,26800000,2.600000e+07,8.0,1,3,5546710,15351,535,1271,48231.0
150,Transformers: Age of Extinction,2014,5.8,1,245000000,2.100000e+08,4233.0,4,0,170909,791,362,230,2814900.0

In [39]:
display(train)

,Movie,Year,Ratings,Genre,Gross,Budget,Screens,Sequel,Sentiment,Views,Likes,Dislikes,Comments,Aggregate Followers
55,Interstellar,2014,8.7,2,188000000,165000000.0,3561.0,1,2,5421705,16635,751,4316,1865000.0
229,War Room,2015,5.4,1,12300000,3000000.0,NaN,1,10,66872,400,67,201,NaN
69,Lucy,2014,6.4,1,127000000,40000000.0,3173.0,1,1,1142964,2346,167,311,NaN
168,Pitch Perfect 2,2015,6.7,8,183000000,29000000.0,3473.0,2,1,9214467,39824,998,1987,7336000.0
109,The Admiral,2014,7.1,2,2590000,9500000.0,1586.0,1,3,134353,280,43,308,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,Tammy,2014,4.8,8,84500000,20000000.0,3465.0,1,0,3429055,7682,675,727,727000.0
14,Atlas Shrugged: Who Is John Galt?,2014,4.4,3,830000,5000000.0,65.0,3,0,595194,85,36,39,15112.0
92,Rio 2,2014,6.4,12,132000000,103000000.0,3948.0,2,4,3849768,9783,704,1151,154400.0
179,Tomorrowland,2015,6.6,12,93200000,190000000.0,3972.0,1,1,999867,4212,66,250,1198000.0
102,Son of God,2014,5.5,9,59700000,22000000.0,3260.0,1,2,943306,3006,325,1401,3185900.0

In [40]:
# https://www.geeksforgeeks.org/python/select-all-columns-except-one-given-column-in-a-pandas-dataframe/
X = df.loc[ : , df.columns != 'Gross']
X.head()

,Movie,Year,Ratings,Genre,Budget,Screens,Sequel,Sentiment,Views,Likes,Dislikes,Comments,Aggregate Followers
0,13 Sins,2014,6.3,8,4000000.0,45.0,1,0,3280543,4632,425,636,1120000.0
1,22 Jump Street,2014,7.1,1,50000000.0,3306.0,2,2,583289,3465,61,186,12350000.0
2,3 Days to Kill,2014,6.2,1,28000000.0,2872.0,1,0,304861,328,34,47,483000.0
3,300: Rise of an Empire,2014,6.3,1,110000000.0,3470.0,2,0,452917,2429,132,590,568000.0
4,A Haunted House 2,2014,4.7,8,3500000.0,2310.0,2,0,3145573,12163,610,1082,1923800.0

In [41]:
y = df['Gross']
y.head()

0         9130
1    192000000
2     30700000
3    106000000
4     17300000
Name: Gross, dtype: int64

In [42]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train:\n", X_train)
print("\nX_test:\n", X_test)
print("\ny_train:\n", y_train)
print("\ny_test:\n", y_test)

X_train:
                                  Movie  Year  Ratings  Genre       Budget  \
55                        Interstellar  2014      8.7      2  165000000.0
229                           War Room  2015      5.4      1    3000000.0
69                                Lucy  2014      6.4      1   40000000.0
168                    Pitch Perfect 2  2015      6.7      8   29000000.0
109                        The Admiral  2014      7.1      2    9500000.0
..                                 ...   ...      ...    ...          ...
106                              Tammy  2014      4.8      8   20000000.0
14   Atlas Shrugged: Who Is John Galt?  2014      4.4      3    5000000.0
92                               Rio 2  2014      6.4     12  103000000.0
179                       Tomorrowland  2015      6.6     12  190000000.0
102                         Son of God  2014      5.5      9   22000000.0

     Screens  Sequel  Sentiment    Views  Likes  Dislikes  Comments  \
55    3561.0       1          2  5421705  16635       751      4316
229      NaN       1         10    66872    400        67       201
69    3173.0       1          1  1142964   2346       167       311
168   3473.0       2          1  9214467  39824       998      1987
109   1586.0       1          3   134353    280        43       308
..       ...     ...        ...      ...    ...       ...       ...
106   3465.0       1          0  3429055   7682       675       727
14      65.0       3          0   595194     85        36        39
92    3948.0       2          4  3849768   9783       704      1151
179   3972.0       1          1   999867   4212        66       250
102   3260.0       1          2   943306   3006       325      1401

     Aggregate Followers
55             1865000.0
229                  NaN
69                   NaN
168            7336000.0
109                  NaN
..                   ...
106             727000.0
14               15112.0
92              154400.0
179            1198000.0
102            3185900.0

[184 rows x 13 columns]

X_test:
                                      Movie  Year  Ratings  Genre  \
218                               Southpaw  2015      7.7      1
66                           Let's Be Cops  2014      6.5      8
9                         About Last Night  2014      6.1      8
170                                   Home  2015      6.7      8
15                                Barefoot  2014      6.6      8
200                            Paper Towns  2015      6.9      3
25                              Cantinflas  2014      6.7      9
196                            Hot Pursuit  2015      5.0      1
154              When the Game Stands Tall  2014      6.6      3
126               The Hundred-Foot Journey  2014      7.3      8
215                              Americons  2015      7.3      3
19                          Black or White  2014      6.6      3
96                                Sabotage  2014      5.7      1
178                             Trainwreck  2015      6.7     12
175                 Straight Outta Compton  2015      8.3      9
137                       The November Man  2014      6.3      1
146                      The Water Diviner  2014      7.2      3
30                               Divergent  2014      6.8      2
226                               Child 44  2015      6.4      4
185                         Magic Mike XXL  2015      6.2      8
108                    That Awkward Moment  2014      6.1      8
162                     Yves Saint Laurent  2014      6.2      9
205                       Hitman: Agent 47  2015      5.9      8
181                     Terminator Genisys  2015      6.8      1
125                           The Homesman  2014      6.6      3
18                              Big Hero 6  2014      7.9     12
147   The Woman in Black 2: Angel of Death  2014      4.9      3
101           Sin City: A Dame to Kill For  2014      6.6     10
104                            St. Vincent  2014      7.3      8
84                                Not Cool  2014      5.2      8
198                          Woman in Gold  2015      7.4     10
60                             Jersey Boys  2014      6.9      9
118                      The Expendables 3  2014      6.1      1
45                               Gone Girl  2014      8.2      3
16         Better Living Through Chemistry  2014      6.3      8
127  The Hunger Games: Mockingjay - Part 1  2014      6.8      2
159                          Winter's Tale  2014      6.2      3
119                 The Fault in Our Stars  2014      7.9      3
82                                    Noah  2014      5.9      1
144                          The Salvation  2014      6.8      3
93                                 RoboCop  2014      6.2      1
194                               The Gift  2015      7.6      1
143                              The Rover  2014      6.4     10
73                         Moms' Night Out  2014      5.4      8
113                       The Book of Life  2014      7.3     12
112                         The Best of Me  2014      6.6      3
150        Transformers: Age of Extinction  2014      5.8      1

           Budget  Screens  Sequel  Sentiment     Views   Likes  Dislikes  \
218  3.000000e+07   2772.0       1          6  11476882   40496      1383
66   1.700000e+07   1534.0       1         -5   4450824    7315       546
9    1.250000e+07   2253.0       1          0   5218079   11709       532
170  1.350000e+08   3708.0       1         -2  10341783   24413      1675
15   6.000000e+06     18.0       1          2   3915978    6983       247
200  1.200000e+07   3031.0       1          6   2854910   23254       459
25   3.000000e+06    382.0       1          3   2902492    9522       558
196  3.500000e+07   3003.0       1          2   6964819   26601      1111
154  1.500000e+07    794.0       1          0    280566     477        56
126  2.200000e+07   2023.0       1         11     24809     277        12
215  4.000000e+06     14.0       1          0     63724     115        28
19   9.000000e+06   1823.0       1         -1   1348142    4404       307
96   3.500000e+07   2486.0       1         17   3466458    6096       411
178  3.500000e+07   3158.0       1          1   9511288   19903      2581
175  2.800000e+07   2757.0       1          5    848970   12607       237
137  1.500000e+07   2776.0       1          0   1935432    3089       155
146  2.250000e+07    320.0       1          7   3281842    4968       445
30   8.500000e+07   3936.0       1         -4    463866    3400       152
226  5.000000e+07     66.0       1          4   3701061    9325       641
185  1.480000e+07   3355.0       2          7   5128288   18475       858
108  8.000000e+06   2809.0       1          0   6132551   14539       653
162  1.200000e+07      2.0       1          0    550734     894        44
205  3.500000e+07   3261.0       1         10  13154873   46684      3565
181  1.550000e+08   3758.0       5          1     84870     265        13
125  1.600000e+07      4.0       1          2     26528      58         1
18   1.650000e+08   3761.0       1         29   4700023   14163       538
147  1.000000e+06   2602.0       2         -6       698      16         1
101  6.500000e+07   2894.0       2          0   5223362   18770       627
104  1.300000e+07     18.0       1         20   4176181    9463       310
84   6.000000e+05      NaN       1          0   5403836  187162      3145
198  1.100000e+07    258.0       1         19      6495      82         3
60   4.000000e+07   2905.0       1         10   1438350    4028       133
118  9.000000e+07     90.0       3          0  14453673   33092      1336
45   6.100000e+07   3014.0       1        -11    396010    1390        58
16   5.000000e+06     25.0       1          0   1391527    2479       146
127  1.250000e+08   4151.0       3          2   3305417   14684       332
159  6.000000e+07   2965.0       1          0    719976    1312        76
119  1.200000e+07   3173.0       1          7  32626778  370552      4752
82   1.250000e+08   3567.0       1          6  13661095   41254      3812
144  1.171231e+07      2.0       1          0    253631     170        11
93   1.000000e+08   3372.0       1          7   3305047   11733      1077
194  5.000000e+06   1648.0       1         11   2513544    6970       270
143  1.225000e+07      5.0       1          0       702       1         0
73   5.000000e+06   1044.0       1          0    667852     469        38
113  5.000000e+07     12.0       1          9   5165441   17476       871
112  2.600000e+07      8.0       1          3   5546710   15351       535
150  2.100000e+08   4233.0       4          0    170909     791       362

     Comments  Aggregate Followers
218      4435                  NaN
66        909            2356000.0
9         770           21697300.0
170      3426            5070000.0
15        460             253000.0
200      1087            4184000.0
25       2296                  NaN
196      1293            1630000.0
154        82             585000.0
126        52              20700.0
215        14             129000.0
19       1033             888000.0
96        977            3678000.0
178      2955            2014000.0
175      1560              55618.0
137       567             148000.0
146      2099            1899400.0
30        987            1030000.0
226      1859                  NaN
185      1579            8392000.0
108       846           11783000.0
162        77             168700.0
205      8578             209000.0
181        63            3877901.0
125         8              25748.0
18       1293             199800.0
147         9               3086.0
101      2796            8620000.0
104       885             269849.0
84      24919            2720000.0
198         7             675000.0
60        543              27323.0
118      5005            1480000.0
45        342           20640000.0
16        182            1658900.0
127      1176           31030000.0
159       189            1810000.0
119     38363            4240000.0
82      18077            1810000.0
144        58                  NaN
93       4319             250000.0
194      1105            1655987.0
143         1               9842.0
73         44             919000.0
113      3229           10364000.0
112      1271              48231.0
150       230            2814900.0

y_train:
 55     188000000
229     12300000
69     127000000
168    183000000
109      2590000
         ...
106     84500000
14        830000
92     132000000
179     93200000
102     59700000
Name: Gross, Length: 184, dtype: int64

y_test:
 218     49500000
66      82400000
9       48600000
170    177000000
15         11800
200     31400000
25       6370000
196     34500000
154     30100000
126     54200000
215       129000
19      21600000
96      10500000
178    105000000
175    135000000
137     25000000
146      4190000
30     151000000
226      1210000
185     65900000
108     26000000
162       717000
205     16100000
181     89400000
125      2430000
18     222000000
147     26500000
101     13800000
104     44100000
84         35700
198     33300000
60      47000000
118     39300000
45     168000000
16         72300
127    337000000
159        22500
119    125000000
82     101000000
144         5000
93      58600000
194     36100000
143      1110000
73      10400000
113     50200000
112     26800000
150    245000000
Name: Gross, dtype: int64